---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 5m
  values:
    cron:
      enabled: true
      schedule: "*/30 * * * *"
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 32Mi
