---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rabbitmq-cluster-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 4.3.22
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    global:
      storageClass: ceph-block
    watchAllNamespaces: false
    watchNamespaces:
      - apps
    resourcesPreset: micro
    networkPolicy:
      kubeAPIServerPorts:
        - 6443
    msgTopologyOperator:
      enabled: false
