---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      uptime-kuma:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.13
              pullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 3001
                protocol: TCP
            resources:
              requests:
                cpu: 10m
                memory: 50Mi
              limits:
                memory: 150Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              readOnlyRootFilesystem: true

        initContainers:
          volumeprep:
            image:
              repository: busybox
              tag: 1.36.1
            command:
              - chown
              - -R
              - 1000:1000
              - /app/data

    service:
      app:
        controller: uptime-kuma
        ports:
          http:
            port: 3001
            protocol: TCP

    ingress:
      app:
        enabled: true
        hosts:
          - host: uptime-kuma.enigma.samoth.eu
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
      data:
        enabled: true
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /app/data
