apiVersion: v1
kind: Secret
metadata:
    name: crunchy-postgres-secret
type: Opaque
data:
    s3.conf: ENC[AES256_GCM,data:33wyknnLR88loGaPISSiPy6INM56vPg6sZowhB/et7EqmP71tSq99hu3LJDSl/TmJd0UNEcRQSeIjm8BwBasHcplgiVsOwtQUAvrcPZ+42MbQKZwT+za+uwljKyJ90wKbS4IfT6jZ0V6mtVyynAVPJ7eX3k3M7zIIiyHP7EzJMfdNMxd+UiYJBaj04ZBRhQo,iv:3B9uUUS67HSTdpf8Il+c3Fr0uMGi00yApHMD5ZgddaM=,tag:P4X58TdLJx1wbcBY50akwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ3VmNnBXS3VmdGF0dXly
            eWdWcFJZT0Vqc0VOTmRrUEdkTTcvWTdBQWxFCnVqSFpCd3Nvc3Zjd05tVUFleXdB
            UFJMZUZhWTQvd29wRExRMXpGc2ZoWEEKLS0tIE9PemtVb0V4TElHUkpZM01oMVNU
            VFhmZ1lvYXJiNm1EOXJzc3JVZzNZOFEKZG29EIq92J/DJzkL+PJPdO5ls2/mK10H
            3PVdYXtIckfU1UqRYFXEF9yV0/v3Wch0r/52hQtHvq6GReXiA7T/Iw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T10:23:08Z"
    mac: ENC[AES256_GCM,data:jVqIoFvlJH+jnVMSwNj8DAI2Adv6zXwromqmSpQ5QxZrLuLJwUV0PmXOMITB1fC9meh8SYXUah/ET/jYRkrQ7nkk9zmiH3pVdyQVQjuHF6kg8YDrLBnSPtwmLRKX93mptqdLY2sUoRWQFtC4MbJpQrgSdqpcvwIIbK1z1nhhL4Y=,iv:Gn7QxVjN3f9y7GBvCKQ3SBOWS/Brmbn8cWTjEzdd6P0=,tag:Ub89wGufpwHhUvoh1PSCBQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
