apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
type: Opaque
data:
    admin-user: ENC[AES256_GCM,data:aUHOW5FwEAQ=,iv:HIor2HZ9VXwItbbVRsN4bYsabJYjVEISPX8TfnjIupk=,tag:+qlzrk7zZo4067dir1/xdg==,type:str]
    admin-password: ENC[AES256_GCM,data:PdtGA4qA9vvF/p8t,iv:yDucCrHcZpswhU3Mn+PtMQExbBFz0R3U/i/qEMIBo40=,tag:fhXxO+4Yha2eZFJesZZdlw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR3RYaThZUGw5Zko5WnJK
            RGI2ajRIb3F2VVFieGx3TkEvS3FYVDI5MFZzCm55bjJhbWE5QjFJTWRJSVRuZlY1
            ejNvaHZmQlJVMW04N0RxNWFLM1Rub3cKLS0tIHNuMElieUtleVljbkZPWUNiTGxY
            a3NQRmEzNjFibk9jcFNYVjUxMy9kcFEKf48F+QE3cgmWGA4t5yP3YNcQi9LvgYin
            SRUoWH2CQlQUKJZ8RE6GqU/P55EPhS8/89k2EZXA75F7RL6A4VltRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-24T19:48:24Z"
    mac: ENC[AES256_GCM,data:TRRL/lhhHi6MedLIQVcz69ibskXL6JrArcEi3VTZ8/MtpQCJyqM9BgXQMaZiL1vEQZu/GLxtpYBDerR3h37Qhc9oZBvrLfg5+jRHkcywfuMavjZfe6e6qFnxKrFZTvO+TWrg8kg79q1eMAfxVYfHukrOwolAFDhXgeBHfvl/gzw=,iv:ilph4lMjEwwOkNp3QKvSBSPZ2QsefynCjGi+n+pN6fs=,tag:+lHGf/MrNjAssq+65ZzOvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
