apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
type: Opaque
data:
    discord_webhook: ENC[AES256_GCM,data:vCW+y91xrKTWlB83cVu6DC/wEe2zLXbBmswLATEaOXj9q+b4Br2Eg3J0KMV3YKseDKGZqJQWN0EHg+sD1OWt7alo4sGPjo7rV9W6540V1uFK0t4biIUNcEsBRCZKhy0pun93/w7jDj7KoO+tNvw8+3nJY788VQ/gvQ==,iv:tVKa56Q2LZwT2TdguLC1BdCwDB9cZIoQKu8ke9w2imc=,tag:Q3u8zvXfqyVXUUxQly3kzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR3RYaThZUGw5Zko5WnJK
            RGI2ajRIb3F2VVFieGx3TkEvS3FYVDI5MFZzCm55bjJhbWE5QjFJTWRJSVRuZlY1
            ejNvaHZmQlJVMW04N0RxNWFLM1Rub3cKLS0tIHNuMElieUtleVljbkZPWUNiTGxY
            a3NQRmEzNjFibk9jcFNYVjUxMy9kcFEKf48F+QE3cgmWGA4t5yP3YNcQi9LvgYin
            SRUoWH2CQlQUKJZ8RE6GqU/P55EPhS8/89k2EZXA75F7RL6A4VltRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T17:15:59Z"
    mac: ENC[AES256_GCM,data:JYc9T1gNTUoMSWXNIVebH4uEA+ISsUkpurCDjmA21OtK2WPL7dhYVzZn9OnHZv1OsGLOVqZYUei81wtcpIgh7ZCc5k+HPdZFVfPnqMdwTynngKwQcGcrqT153Gyn8Ogr4O8Hmw6lXbPibcc2FGQSibWmIlE59ellqkefakmzTmg=,iv:ixlCur7dVkbZ1BOIc0wol7KVCn7pH9fUrE34PXXGfls=,tag:smghMtkGX4rNBilp/St02w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
