---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./alertmanager/ks.yaml
  - ./prometheus-operator-crds/ks.yaml
  - ./kube-state-metrics/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./node-exporter/ks.yaml
  - ./grafana/ks.yaml
