apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:2+EJ9rA+uitQSrXDdf1JB7M4u6iwQCa9+LRTcmLsb+sRHCr2rnLiwlnvUYuwaWNvp9t/iPVZ8VqPYtgFCUuCCuEgxd86F+uAgYfHy75WWVwR,iv:zQx98nZS/024cL5nF8A/6IdEQJQkcYzxZtouPjcDfKE=,tag:vFcyJRJhhHpiPn3/yajEag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoYXNoS3A2VHRUYmVLT0kv
            K3VDVUtTWGVLVWp5M3o4TzZ4VkhsUWdlMlFFClp5TnpUaTVSclJaeVFFdkQraDBy
            YkNKdldsd2xlVXd6L0NYYTBvVlFqVkUKLS0tIFNxR1N2ZGRjM3RhZXV4dEo4OHRv
            UDY1RGkzUEpjYndIdkpjdW9jY1QycGcKsLLg+kQVToKR//Zcm011XQa9CbuTblBn
            hVqrm48JfJqnVLCbGITsftZEimnPsNPwpf3JjA+D36nVWmk/9/fbGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T18:51:23Z"
    mac: ENC[AES256_GCM,data:911N1YRW1bvE/SIfOnPZ67RK1NcaAYtzPDv0h6Twcvm0w8Vjj9W7cB0hjmi6+2mrbbknKP8ZDK6C2FleiOzos2IG+ofih5TIxvybuN/RzC/x4SX/cAe41XpXsSFkfnPAmiX8PAb/+3SnkFXSTh2EtS77dIxEvECsLrWqu39w3T4=,iv:IiXbyixsiNzE+EZYKjSSCWgxHXKdrzHpri2OwNLj8OA=,tag:jqCNADFWQMHMQO6wgEC4Vw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
