apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:Cmy8Hjh8Rh9Pd7K0/7/R20uXAfkCB05oHp07tOMtyKVU2Y00VMANjL53DQv+BdypKR5Y9u5uE3XiU2IWGJyO+UrMg5/j3pZcNdadadMzrR+N,iv:4pcf61ejefDO9P4b13VrQZQybrCA2kFB7ZsRGiY44qM=,tag:MkbagRLg9dHJCYecLosJ+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMXkzWmxNaEcrVzJVSndT
            VUlkSXZMaUd3cExDVHpCM2V1Z2dkZC9WWUdnCmtzb1dFYVdyZUJuNGVsOXB3bXZG
            Wm9ERXJIak5JNjdJanJXSWN1ZnU2R0kKLS0tIDlDamVwUWdKNUFxTnNqUGRZSDZD
            SklDd21lOUVHQ1ZsNUw5bjM1S1FXZzQKyKsKi59a7Zqe6U1nWjCY51o6H3aomAza
            YEyu2mpa892aJmbS2s4Nu2A5IIDa4RBvqMwk7IhcJi3Sb8QCQ3DHPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-27T20:53:03Z"
    mac: ENC[AES256_GCM,data:QUiXHbk4Hx1N/3D8frKBf5L0EYC1s9yjK1Q5X5+Pt70GwrS1JS34UVvSedDQvqAeBCgj/b3r9bbtjTE+jO18eStgNEoAXGRZ8i4IexTCHz9T1AaAMuY7UQhJF2CeQUApSxXI+/K8NyzeDy9s2DDdoWiyHq3ryxaSAVAdNGrXEEk=,iv:Xgzc97061i884TlGJBZ9TMnXcNe+CN38+tzuAQDdyhk=,tag:dePIxAgMMkXpLNePZw2FnQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
