apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:hkfR5g6bZq9xHEdSZcT79JzrfO33owoOecbuSAazVudSjPBZ2KvnLl85+4T2sCHcj1LHUfvazl/V2mNWTQduDhp08FfM5IDTqXGKS827IZcl,iv:124GXRy0W52NQAYsNAhvA45Lybox8kqQSwcKG7iPFWk=,tag:SoJJhriaMjUMmACeNB8kxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tjsw23yzl9m8gc8zsexypje8vfqcrjmvmd4j6catcea73qglv32qeh6n27
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtdk1UWjNEMkVIM0doNGJj
            SGN5Wlc0c3FuNEUvS01kcjN3MFZScG9tTlM4ClBmY05UUXFDc3pvaEwxcVk3ODlI
            NzRnTWtRdk9yOEZjbCttNnJlUmZXeDQKLS0tIG5SaGJVV04wT05uRVRBOU52Wk5j
            SDRheUZsTHkyWVB4cHl2UmUwQWZVdjAKralROt7NmqTk8sriX4DKSASpwEUcypbC
            +lRB1uIhZPpF3w0JXbOP09AEahdkrajXkBDP4YR6J3fOLMXuNBENrQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-24T20:34:12Z"
    mac: ENC[AES256_GCM,data:ZBN7+pq49z+BFH9mB5L92mNKV+TPxGkpgAdnoZUJB69u9rZwd4frlTdHIZoE/n2tQLg/lOkpX57KktD+JGwHwfUJhpbGz20k5Yzgagk4lbfpT51Wli04PalG1xLASMxWm+3+cPu6GVE6LTOOaXGFqR0vRqrZ2C8EEEbkl3EGAao=,iv:iJ8hYxCfBBewz69qPpQmWVAsLmLBv9V+jMMcvfCRdTA=,tag:kFS69W5nSJURlV6CLAmqbA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
