---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: harbor
spec:
  interval: 30m
  chart:
    spec:
      chart: harbor
      version: 1.15.1
      sourceRef:
        kind: HelmRepository
        name: harbor
        namespace: flux-system
      interval: 5m
  values:
    expose:
      ingress:
        hosts:
          core: harbor.enigma.samoth.eu
    database:
      type: external
      external:
        host: postgres-pgbouncer.database.svc
        username: harbor
        coreDatabase: harbor
        existing-secret: database/postgres-pguser-harbor
        sslmode: require
